<a href="https://colab.research.google.com/github/asteriaji/MSSP6070/blob/main/WeeklyModules/Week05/Jiangyu_Ji_PARTICIPATION_ACTIVITY_Week_5_Merge_two_Pandas_dataframes__0930_(2).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [20]:
import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
import statsmodels.formula.api as sm
import statsmodels.api as se
import seaborn as sns
import datetime as dt
from sklearn.linear_model import LinearRegression
from scipy import stats
from io import StringIO
import itertools
import os
import subprocess
from pathlib import Path

pd.set_eng_float_format(accuracy=3, use_eng_prefix=True)
pd.set_option('display.float_format', lambda x: '%.2f' % x)

owner = 'asteriaji'
repository = 'MSSP6070'
repo_url = f'https://github.com/{owner}/{repository}.git'
repo_path = Path('/content') / repository

if not repo_path.exists():
    subprocess.run(
        ['git', 'clone', repo_url, str(repo_path)],
        check=True
    )
else:
    print("Repository already exists. Using the existing copy.")

os.chdir(repo_path)

print("Current directory:", os.getcwd())

print("Files in repository:")
for item in sorted(repo_path.rglob('*')):
    if item.is_file() and '.git' not in item.parts:
        print(item.relative_to(repo_path))

Repository already exists. Using the existing copy.
Current directory: /content/MSSP6070
Files in repository:
Adding_File_Structure.py
Assignments/.gitkeep
Assignments/Assignment 1/Corrected_Version_Jiangyu_Ji_MSSP_6070_Assignment_1.ipynb
Assignments/Assignment 1/Jiangyu_Ji_MSSP_6070_Assignment_1_260930.ipynb
Assignments/Assignment 2/1
MSSP6070/Adding_File_Structure.py
MSSP6070/Assignments/.gitkeep
MSSP6070/Assignments/Assignment 1/Corrected_Version_Jiangyu_Ji_MSSP_6070_Assignment_1.ipynb
MSSP6070/Assignments/Assignment 1/Jiangyu_Ji_MSSP_6070_Assignment_1_260930.ipynb
MSSP6070/Assignments/Assignment 2/1
MSSP6070/WeeklyModules/.gitkeep
MSSP6070/WeeklyModules/Week01/.gitkeep
MSSP6070/WeeklyModules/Week01/1_introducing_matplotlib_(1).ipynb
MSSP6070/WeeklyModules/Week01/Week1_Jiangyu_Ji_Participation_Activity_Exercises_260828.ipynb
MSSP6070/WeeklyModules/Week01/stats_viz (1).py
MSSP6070/WeeklyModules/Week02/.gitkeep
MSSP6070/WeeklyModules/Week02/Week2_Jiangyu_Ji_Participation_Activity_260907__(2).ipynb
MSSP6070/WeeklyModules/Week02/Week_2_Data_Stuctures.ipynb
MSSP6070/WeeklyModules/Week03/.gitkeep
MSSP6070/WeeklyModules/Week03/Week_3_Jiangyu_Ji_PARTICIPATION_ACTIVITY_(3)_(2).ipynb
MSSP6070/WeeklyModules/Week04/.gitkeep
MSSP6070/WeeklyModules/Week04/Jiangyu_Ji_Assignment_PARTICIPATION_ACTIVITY_Week_4_Opening_a_CSV_file_and_modifying_the_contents__260920(1).ipynb
MSSP6070/WeeklyModules/Week05/.gitkeep
MSSP6070/WeeklyModules/Week05/Jiangyu_Ji_PARTICIPATION_ACTIVITY_Week_5_Merge_two_Pandas_dataframes__0930_(2).ipynb
MSSP6070/WeeklyModules/Week06/.gitkeep
MSSP6070/WeeklyModules/Week06/Jiangyu_Ji_PARTICIPATION_ACTIVITY_Week_6_Write_a_lamda_function_for_a_dataframe_(1).ipynb
MSSP6070/WeeklyModules/Week07/.gitkeep
MSSP6070/WeeklyModules/Week07/Jiangyu_Ji_PARTICIPATION_ACTIVITY_Week_7_Export_a_bar_chart_from_a_data_frame_to_a_PDF.ipynb
MSSP6070/WeeklyModules/Week07/yearly_sales (2) (1).pdf
MSSP6070/WeeklyModules/Week08/.gitkeep
MSSP6070/WeeklyModules/Week09/.gitkeep
MSSP6070/WeeklyModules/Week10/.gitkeep
MSSP6070/WeeklyModules/Week11/.gitkeep
MSSP6070/WeeklyModules/Week12/.gitkeep
MSSP6070/WeeklyModules/Week13/.gitkeep
MSSP6070/WeeklyModules/Week14/.gitkeep
MSSP6070/data/.gitkeep
MSSP6070/data/Assignment 1/data_academic_performance.xlsx
MSSP6070/data/Assignment 2/InternetSales (2).csv
MSSP6070/data/Enrollment_Forecast.ipynb
MSSP6070/data/Google_connection.py
MSSP6070/data/InternetSales.csv
MSSP6070/data/Student Performance Data.csv
MSSP6070/data/Week 05 Examples/aapl.csv
MSSP6070/data/Week 05 Examples/amzn.csv
MSSP6070/data/Week 05 Examples/faanf.csv
MSSP6070/data/Week 05 Examples/fb.csv
MSSP6070/data/Week 05 Examples/goog.csv
MSSP6070/data/Week 05 Examples/nflx.csv
MSSP6070/data/parsed.csv
MSSP6070/data/parsed_origin.csv
MSSP6070/data/yearly_sales (1).pdf
MSSP6070/faanf.csv
WeeklyModules/.gitkeep
WeeklyModules/Week01/.gitkeep
WeeklyModules/Week01/1_introducing_matplotlib_(1).ipynb
WeeklyModules/Week01/Week1_Jiangyu_Ji_Participation_Activity_Exercises_260828.ipynb
WeeklyModules/Week01/stats_viz (1).py
WeeklyModules/Week02/.gitkeep
WeeklyModules/Week02/Week2_Jiangyu_Ji_Participation_Activity_260907__(2).ipynb
WeeklyModules/Week02/Week_2_Data_Stuctures.ipynb
WeeklyModules/Week03/.gitkeep
WeeklyModules/Week03/Week_3_Jiangyu_Ji_PARTICIPATION_ACTIVITY_(3)_(2).ipynb
WeeklyModules/Week04/.gitkeep
WeeklyModules/Week04/Jiangyu_Ji_Assignment_PARTICIPATION_ACTIVITY_Week_4_Opening_a_CSV_file_and_modifying_the_contents__260920(1).ipynb
WeeklyModules/Week05/.gitkeep
WeeklyModules/Week05/Jiangyu_Ji_PARTICIPATION_ACTIVITY_Week_5_Merge_two_Pandas_dataframes__0930_(2).ipynb
WeeklyModules/Week06/.gitkeep
WeeklyModules/Week06/Jiangyu_Ji_PARTICIPATION_ACTIVITY_Week_6_Write_a_lamda_function_for_a_dataframe_(1).ipynb
WeeklyModules/Week07/.gitkeep
WeeklyModules/Week07/Jiangyu_Ji_PARTICIPATION_ACTIVITY_Week_7_Export_a_bar_chart_from_a_data_frame_to_a_PDF.ipynb
WeeklyModules/Week07/yearly_sales (2) (1).pdf
WeeklyModules/Week08/.gitkeep
WeeklyModules/Week09/.gitkeep
WeeklyModules/Week10/.gitkeep
WeeklyModules/Week11/.gitkeep
WeeklyModules/Week12/.gitkeep
WeeklyModules/Week13/.gitkeep
WeeklyModules/Week14/.gitkeep
data/.gitkeep
data/Assignment 1/data_academic_performance.xlsx
data/Assignment 2/InternetSales (2).csv
data/Enrollment_Forecast.ipynb
data/Google_connection.py
data/InternetSales.csv
data/Student Performance Data.csv
data/Week 05 Examples/aapl.csv
data/Week 05 Examples/amzn.csv
data/Week 05 Examples/faanf.csv
data/Week 05 Examples/fb.csv
data/Week 05 Examples/goog.csv
data/Week 05 Examples/nflx.csv
data/parsed.csv
data/parsed_origin.csv
data/yearly_sales (1).pdf

In [3]:
# 1.a.
!git clone https://github.com/asteriaji/MSSP6070.git

Cloning into 'MSSP6070'...
remote: Enumerating objects: 699, done.
remote: Counting objects: 100% (135/135), done.
remote: Compressing objects: 100% (109/109), done.
remote: Total 699 (delta 78), reused 23 (delta 23), pack-reused 564 (from 1)
Receiving objects: 100% (699/699), 22.06 MiB | 10.32 MiB/s, done.
Resolving deltas: 100% (351/351), done.

In [4]:
%cd MSSP6070

/content/MSSP6070/MSSP6070

In [5]:
import pandas as pd

aapl = pd.read_csv("data/Week 05 Examples/aapl.csv")
amzn = pd.read_csv("data/Week 05 Examples/amzn.csv")
nflx = pd.read_csv("data/Week 05 Examples/nflx.csv")
fb = pd.read_csv("data/Week 05 Examples/fb.csv")
goog = pd.read_csv("data/Week 05 Examples/goog.csv")

In [6]:
aapl.columns
amzn.columns
nflx.columns
fb.columns
goog.columns

Index(['date', 'open', 'high', 'low', 'close', 'volume'], dtype='object')

In [7]:
# 2.a.
df = pd.concat([aapl, amzn, nflx, fb, goog], ignore_index=True)
df

            date    open    high     low   close    volume
0     2018-01-02  166.93  169.03  166.04  168.99  25555934
1     2018-01-03  169.25  171.23  168.69  168.96  29517899
2     2018-01-04  169.26  170.17  168.81  169.74  22434597
3     2018-01-05  170.14  172.04  169.76  171.68  23660018
4     2018-01-08  171.04  172.27  170.63  171.04  20567766
...          ...     ...     ...     ...     ...       ...
1250  2018-12-24  973.90 1003.54  970.11  976.22   1590328
1251  2018-12-26  989.01 1040.00  983.00 1039.46   2373270
1252  2018-12-27 1017.15 1043.89  997.00 1043.88   2109777
1253  2018-12-28 1049.62 1055.56 1033.10 1037.08   1413772
1254  2018-12-31 1050.96 1052.70 1023.59 1035.61   1493722

[1255 rows x 6 columns]

In [8]:
# 2.b.
import pandas as pd

aapl = pd.read_csv("data/Week 05 Examples/aapl.csv")
amzn = pd.read_csv("data/Week 05 Examples/amzn.csv")
nflx = pd.read_csv("data/Week 05 Examples/nflx.csv")
fb = pd.read_csv("data/Week 05 Examples/fb.csv")
goog = pd.read_csv("data/Week 05 Examples/goog.csv")

In [9]:
aapl.head()

         date   open   high    low  close    volume
0  2018-01-02 166.93 169.03 166.04 168.99  25555934
1  2018-01-03 169.25 171.23 168.69 168.96  29517899
2  2018-01-04 169.26 170.17 168.81 169.74  22434597
3  2018-01-05 170.14 172.04 169.76 171.68  23660018
4  2018-01-08 171.04 172.27 170.63 171.04  20567766

In [10]:
amzn.head()

         date    open    high     low   close   volume
0  2018-01-02 1172.00 1190.00 1170.51 1189.01  2694494
1  2018-01-03 1188.30 1205.49 1188.30 1204.20  3108793
2  2018-01-04 1205.00 1215.87 1204.66 1209.59  3022089
3  2018-01-05 1217.51 1229.14 1210.00 1229.14  3544743
4  2018-01-08 1236.00 1253.08 1232.03 1246.87  4279475

In [11]:
nflx.head()

         date   open   high    low  close    volume
0  2018-01-02 196.10 201.65 195.42 201.07  10966889
1  2018-01-03 202.05 206.21 201.50 205.05   8591369
2  2018-01-04 206.20 207.05 204.00 205.63   6029616
3  2018-01-05 207.25 210.02 205.59 209.99   7033240
4  2018-01-08 210.02 212.50 208.44 212.05   5580178

In [12]:
fb.head()

         date   open   high    low  close    volume
0  2018-01-02 177.68 181.58 177.55 181.42  18151903
1  2018-01-03 181.88 184.78 181.33 184.67  16886563
2  2018-01-04 184.90 186.21 184.10 184.33  13880896
3  2018-01-05 185.59 186.90 184.93 186.85  13574535
4  2018-01-08 187.20 188.90 186.33 188.28  17994726

In [13]:
goog.head()

         date    open    high     low   close   volume
0  2018-01-02 1048.34 1066.94 1045.23 1065.00  1237564
1  2018-01-03 1064.31 1086.29 1063.21 1082.48  1430170
2  2018-01-04 1088.00 1093.57 1084.00 1086.40  1004605
3  2018-01-05 1094.00 1104.25 1092.00 1102.23  1279123
4  2018-01-08 1102.23 1111.27 1101.62 1106.94  1047603

In [14]:
# 2.c.
aapl['ticker'] = "AAPL"
amzn['ticker'] = "AMZN"
nflx['ticker'] = "NFLX"
fb['ticker'] = "FB"
goog['ticker'] = "GOOG"

display(aapl.head())
display(amzn.head())
display(nflx.head())
display(fb.head())
display(goog.head())

         date   open   high    low  close    volume ticker
0  2018-01-02 166.93 169.03 166.04 168.99  25555934   AAPL
1  2018-01-03 169.25 171.23 168.69 168.96  29517899   AAPL
2  2018-01-04 169.26 170.17 168.81 169.74  22434597   AAPL
3  2018-01-05 170.14 172.04 169.76 171.68  23660018   AAPL
4  2018-01-08 171.04 172.27 170.63 171.04  20567766   AAPL

         date    open    high     low   close   volume ticker
0  2018-01-02 1172.00 1190.00 1170.51 1189.01  2694494   AMZN
1  2018-01-03 1188.30 1205.49 1188.30 1204.20  3108793   AMZN
2  2018-01-04 1205.00 1215.87 1204.66 1209.59  3022089   AMZN
3  2018-01-05 1217.51 1229.14 1210.00 1229.14  3544743   AMZN
4  2018-01-08 1236.00 1253.08 1232.03 1246.87  4279475   AMZN

         date   open   high    low  close    volume ticker
0  2018-01-02 196.10 201.65 195.42 201.07  10966889   NFLX
1  2018-01-03 202.05 206.21 201.50 205.05   8591369   NFLX
2  2018-01-04 206.20 207.05 204.00 205.63   6029616   NFLX
3  2018-01-05 207.25 210.02 205.59 209.99   7033240   NFLX
4  2018-01-08 210.02 212.50 208.44 212.05   5580178   NFLX

         date   open   high    low  close    volume ticker
0  2018-01-02 177.68 181.58 177.55 181.42  18151903     FB
1  2018-01-03 181.88 184.78 181.33 184.67  16886563     FB
2  2018-01-04 184.90 186.21 184.10 184.33  13880896     FB
3  2018-01-05 185.59 186.90 184.93 186.85  13574535     FB
4  2018-01-08 187.20 188.90 186.33 188.28  17994726     FB

         date    open    high     low   close   volume ticker
0  2018-01-02 1048.34 1066.94 1045.23 1065.00  1237564   GOOG
1  2018-01-03 1064.31 1086.29 1063.21 1082.48  1430170   GOOG
2  2018-01-04 1088.00 1093.57 1084.00 1086.40  1004605   GOOG
3  2018-01-05 1094.00 1104.25 1092.00 1102.23  1279123   GOOG
4  2018-01-08 1102.23 1111.27 1101.62 1106.94  1047603   GOOG

In [15]:
# 2.d.
df = pd.concat([aapl, amzn, nflx, fb, goog], ignore_index=True)
df

            date    open    high     low   close    volume ticker
0     2018-01-02  166.93  169.03  166.04  168.99  25555934   AAPL
1     2018-01-03  169.25  171.23  168.69  168.96  29517899   AAPL
2     2018-01-04  169.26  170.17  168.81  169.74  22434597   AAPL
3     2018-01-05  170.14  172.04  169.76  171.68  23660018   AAPL
4     2018-01-08  171.04  172.27  170.63  171.04  20567766   AAPL
...          ...     ...     ...     ...     ...       ...    ...
1250  2018-12-24  973.90 1003.54  970.11  976.22   1590328   GOOG
1251  2018-12-26  989.01 1040.00  983.00 1039.46   2373270   GOOG
1252  2018-12-27 1017.15 1043.89  997.00 1043.88   2109777   GOOG
1253  2018-12-28 1049.62 1055.56 1033.10 1037.08   1413772   GOOG
1254  2018-12-31 1050.96 1052.70 1023.59 1035.61   1493722   GOOG

[1255 rows x 7 columns]

In [16]:
# 2.e.
faanf = pd.concat([aapl, amzn, nflx, fb, goog], ignore_index=True)
faanf.to_csv("faanf.csv", index=False)
faanf.head()

         date   open   high    low  close    volume ticker
0  2018-01-02 166.93 169.03 166.04 168.99  25555934   AAPL
1  2018-01-03 169.25 171.23 168.69 168.96  29517899   AAPL
2  2018-01-04 169.26 170.17 168.81 169.74  22434597   AAPL
3  2018-01-05 170.14 172.04 169.76 171.68  23660018   AAPL
4  2018-01-08 171.04 172.27 170.63 171.04  20567766   AAPL

In [17]:
# 2.f.
faanf['date'] = pd.to_datetime(faanf['date'])
display(faanf['date'].dtype)
faanf['volume'] = faanf['volume'].astype(int)
display(faanf['volume'].dtype)

faanf = faanf.sort_values(by=['date', 'ticker'])
display(faanf.head())

dtype('<M8[ns]')

dtype('int64')

           date    open    high     low   close    volume ticker
0    2018-01-02  166.93  169.03  166.04  168.99  25555934   AAPL
251  2018-01-02 1172.00 1190.00 1170.51 1189.01   2694494   AMZN
753  2018-01-02  177.68  181.58  177.55  181.42  18151903     FB
1004 2018-01-02 1048.34 1066.94 1045.23 1065.00   1237564   GOOG
502  2018-01-02  196.10  201.65  195.42  201.07  10966889   NFLX

In [18]:
# 2.g.
faanf = faanf.sort_values(by=['volume'], ascending=False)
print('The 7 rows within the highest value for volume:')
display(faanf.head(7))

The 7 rows within the highest value for volume:

          date   open   high    low  close     volume ticker
895 2018-07-26 174.89 180.13 173.75 176.26  169803668     FB
806 2018-03-20 167.47 170.20 161.95 168.15  129851768     FB
810 2018-03-26 160.82 161.10 149.02 160.06  126116634     FB
807 2018-03-21 164.80 173.40 163.30 169.39  106598834     FB
182 2018-09-21 219.07 219.65 215.61 215.98   96246748   AAPL
245 2018-12-21 156.19 157.48 148.99 150.09   95744384   AAPL
212 2018-11-02 207.93 212.00 203.84 205.88   91328654   AAPL

In [19]:
# 2.h.
faanf = faanf.sort_values(by=['date', 'ticker'])
faanf.melt(id_vars=["date", "ticker"])

           date ticker variable       value
0    2018-01-02   AAPL     open      166.93
1    2018-01-02   AMZN     open     1172.00
2    2018-01-02     FB     open      177.68
3    2018-01-02   GOOG     open     1048.34
4    2018-01-02   NFLX     open      196.10
...         ...    ...      ...         ...
6270 2018-12-31   AAPL   volume 35003466.00
6271 2018-12-31   AMZN   volume  6954507.00
6272 2018-12-31     FB   volume 24625308.00
6273 2018-12-31   GOOG   volume  1493722.00
6274 2018-12-31   NFLX   volume 13508920.00

[6275 rows x 4 columns]