<a href="https://colab.research.google.com/github/asteriaji/MSSP6070/blob/main/Assignments/Week%205/Jiangyu_Ji_PARTICIPATION_ACTIVITY_Week_5_Merge_two_Pandas_dataframes_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [34]:
# 1.a.
!git clone https://github.com/asteriaji/MSSP6070.git

Cloning into 'MSSP6070'...
remote: Enumerating objects: 420, done.
remote: Counting objects: 100% (103/103), done.
remote: Compressing objects: 100% (80/80), done.
remote: Total 420 (delta 62), reused 23 (delta 23), pack-reused 317 (from 3)
Receiving objects: 100% (420/420), 2.52 MiB | 13.46 MiB/s, done.
Resolving deltas: 100% (172/172), done.

In [35]:
%cd MSSP6070

/content/MSSP6070/MSSP6070/MSSP6070/MSSP6070

In [36]:
import pandas as pd

aapl = pd.read_csv("data/Week 05 Examples/aapl.csv")
amzn = pd.read_csv("data/Week 05 Examples/amzn.csv")
nflx = pd.read_csv("data/Week 05 Examples/nflx.csv")
fb = pd.read_csv("data/Week 05 Examples/fb.csv")
goog = pd.read_csv("data/Week 05 Examples/goog.csv")

In [37]:
aapl.columns
amzn.columns
nflx.columns
fb.columns
goog.columns

Index(['date', 'open', 'high', 'low', 'close', 'volume'], dtype='object')

In [38]:
# 2.a.
df = pd.concat([aapl, amzn, nflx, fb, goog], ignore_index=True)
df

            date       open       high        low      close    volume
0     2018-01-02   166.9271   169.0264   166.0442   168.9872  25555934
1     2018-01-03   169.2521   171.2337   168.6929   168.9578  29517899
2     2018-01-04   169.2619   170.1742   168.8106   169.7426  22434597
3     2018-01-05   170.1448   172.0381   169.7622   171.6751  23660018
4     2018-01-08   171.0375   172.2736   170.6255   171.0375  20567766
...          ...        ...        ...        ...        ...       ...
1250  2018-12-24   973.9000  1003.5400   970.1100   976.2200   1590328
1251  2018-12-26   989.0100  1040.0000   983.0000  1039.4600   2373270
1252  2018-12-27  1017.1500  1043.8900   997.0000  1043.8800   2109777
1253  2018-12-28  1049.6200  1055.5600  1033.1000  1037.0800   1413772
1254  2018-12-31  1050.9600  1052.7000  1023.5900  1035.6100   1493722

[1255 rows x 6 columns]

In [39]:
# 2.b.
import pandas as pd

aapl = pd.read_csv("data/Week 05 Examples/aapl.csv")
amzn = pd.read_csv("data/Week 05 Examples/amzn.csv")
nflx = pd.read_csv("data/Week 05 Examples/nflx.csv")
fb = pd.read_csv("data/Week 05 Examples/fb.csv")
goog = pd.read_csv("data/Week 05 Examples/goog.csv")

In [40]:
# 2.c.
aapl['ticker'] = "AAPL"
amzn['ticker'] = "AMZN"
nflx['ticker'] = "NFLX"
fb['ticker'] = "FB"
goog['ticker'] = "GOOG"

display(aapl.head())
display(amzn.head())
display(nflx.head())
display(fb.head())
display(goog.head())

         date      open      high       low     close    volume ticker
0  2018-01-02  166.9271  169.0264  166.0442  168.9872  25555934   AAPL
1  2018-01-03  169.2521  171.2337  168.6929  168.9578  29517899   AAPL
2  2018-01-04  169.2619  170.1742  168.8106  169.7426  22434597   AAPL
3  2018-01-05  170.1448  172.0381  169.7622  171.6751  23660018   AAPL
4  2018-01-08  171.0375  172.2736  170.6255  171.0375  20567766   AAPL

         date     open     high      low    close   volume ticker
0  2018-01-02  1172.00  1190.00  1170.51  1189.01  2694494   AMZN
1  2018-01-03  1188.30  1205.49  1188.30  1204.20  3108793   AMZN
2  2018-01-04  1205.00  1215.87  1204.66  1209.59  3022089   AMZN
3  2018-01-05  1217.51  1229.14  1210.00  1229.14  3544743   AMZN
4  2018-01-08  1236.00  1253.08  1232.03  1246.87  4279475   AMZN

         date    open    high       low   close    volume ticker
0  2018-01-02  196.10  201.65  195.4200  201.07  10966889   NFLX
1  2018-01-03  202.05  206.21  201.5000  205.05   8591369   NFLX
2  2018-01-04  206.20  207.05  204.0006  205.63   6029616   NFLX
3  2018-01-05  207.25  210.02  205.5900  209.99   7033240   NFLX
4  2018-01-08  210.02  212.50  208.4400  212.05   5580178   NFLX

         date    open    high       low   close    volume ticker
0  2018-01-02  177.68  181.58  177.5500  181.42  18151903     FB
1  2018-01-03  181.88  184.78  181.3300  184.67  16886563     FB
2  2018-01-04  184.90  186.21  184.0996  184.33  13880896     FB
3  2018-01-05  185.59  186.90  184.9300  186.85  13574535     FB
4  2018-01-08  187.20  188.90  186.3300  188.28  17994726     FB

         date     open     high      low    close   volume ticker
0  2018-01-02  1048.34  1066.94  1045.23  1065.00  1237564   GOOG
1  2018-01-03  1064.31  1086.29  1063.21  1082.48  1430170   GOOG
2  2018-01-04  1088.00  1093.57  1084.00  1086.40  1004605   GOOG
3  2018-01-05  1094.00  1104.25  1092.00  1102.23  1279123   GOOG
4  2018-01-08  1102.23  1111.27  1101.62  1106.94  1047603   GOOG

In [41]:
# 2.d.
df = pd.concat([aapl, amzn, nflx, fb, goog], ignore_index=True)
df

            date       open       high        low      close    volume ticker
0     2018-01-02   166.9271   169.0264   166.0442   168.9872  25555934   AAPL
1     2018-01-03   169.2521   171.2337   168.6929   168.9578  29517899   AAPL
2     2018-01-04   169.2619   170.1742   168.8106   169.7426  22434597   AAPL
3     2018-01-05   170.1448   172.0381   169.7622   171.6751  23660018   AAPL
4     2018-01-08   171.0375   172.2736   170.6255   171.0375  20567766   AAPL
...          ...        ...        ...        ...        ...       ...    ...
1250  2018-12-24   973.9000  1003.5400   970.1100   976.2200   1590328   GOOG
1251  2018-12-26   989.0100  1040.0000   983.0000  1039.4600   2373270   GOOG
1252  2018-12-27  1017.1500  1043.8900   997.0000  1043.8800   2109777   GOOG
1253  2018-12-28  1049.6200  1055.5600  1033.1000  1037.0800   1413772   GOOG
1254  2018-12-31  1050.9600  1052.7000  1023.5900  1035.6100   1493722   GOOG

[1255 rows x 7 columns]

In [46]:
# 2.e.
faanf = pd.concat([aapl, amzn, nflx, fb, goog], ignore_index=True)
faanf.to_csv("faanf.csv", index=False)
faanf.head()

         date      open      high       low     close    volume ticker
0  2018-01-02  166.9271  169.0264  166.0442  168.9872  25555934   AAPL
1  2018-01-03  169.2521  171.2337  168.6929  168.9578  29517899   AAPL
2  2018-01-04  169.2619  170.1742  168.8106  169.7426  22434597   AAPL
3  2018-01-05  170.1448  172.0381  169.7622  171.6751  23660018   AAPL
4  2018-01-08  171.0375  172.2736  170.6255  171.0375  20567766   AAPL

In [47]:
# 2.f.
faanf['date'] = pd.to_datetime(faanf['date'])
display(faanf['date'].dtype)
faanf['volume'] = faanf['volume'].astype(int)
display(faanf['volume'].dtype)

faanf = faanf.sort_values(by=['date', 'ticker'])
display(faanf.head())

dtype('<M8[ns]')

dtype('int64')

           date       open       high        low      close    volume ticker
0    2018-01-02   166.9271   169.0264   166.0442   168.9872  25555934   AAPL
251  2018-01-02  1172.0000  1190.0000  1170.5100  1189.0100   2694494   AMZN
753  2018-01-02   177.6800   181.5800   177.5500   181.4200  18151903     FB
1004 2018-01-02  1048.3400  1066.9400  1045.2300  1065.0000   1237564   GOOG
502  2018-01-02   196.1000   201.6500   195.4200   201.0700  10966889   NFLX

In [48]:
# 2.g.
faanf = faanf.sort_values(by=['volume'], ascending=False)
print('The 7 rows within the highest value for volume:')
display(faanf.head(7))

The 7 rows within the highest value for volume:

          date      open      high       low     close     volume ticker
895 2018-07-26  174.8900  180.1300  173.7500  176.2600  169803668     FB
806 2018-03-20  167.4700  170.2000  161.9500  168.1500  129851768     FB
810 2018-03-26  160.8200  161.1000  149.0200  160.0600  126116634     FB
807 2018-03-21  164.8000  173.4000  163.3000  169.3900  106598834     FB
182 2018-09-21  219.0727  219.6482  215.6097  215.9768   96246748   AAPL
245 2018-12-21  156.1901  157.4845  148.9909  150.0862   95744384   AAPL
212 2018-11-02  207.9295  211.9978  203.8414  205.8755   91328654   AAPL

In [49]:
# 2.h.
faanf.melt(id_vars= ['date','ticker'])

           date ticker variable        value
0    2018-07-26     FB     open     174.8900
1    2018-03-20     FB     open     167.4700
2    2018-03-26     FB     open     160.8200
3    2018-03-21     FB     open     164.8000
4    2018-09-21   AAPL     open     219.0727
...         ...    ...      ...          ...
6270 2018-08-09   GOOG   volume  848601.0000
6271 2018-07-10   GOOG   volume  798412.0000
6272 2018-05-24   GOOG   volume  766773.0000
6273 2018-11-23   GOOG   volume  691462.0000
6274 2018-07-03   GOOG   volume  679034.0000

[6275 rows x 4 columns]